name: Automation Test CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Chrome + Driver
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver

      - name: Grant permission
        run: chmod +x gradlew

      - name: Run Test
        run: ./gradlew clean test

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: app/build/reports/